esphome:
  name: esp-hobby-room-sitting-timer
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable I2C
i2c:
  sda: D1
  scl: D2
  scan: true  # This will log detected I2C devices in the ESPHome logs

# LCD Display
display:
  - platform: lcd_pcf8574
    id: my_lcd
    address: 0x27  # Common address; check logs if different
    dimensions: 16x2  # Required option for specifying LCD size
    update_interval: 1s
    lambda: |-
      it.print(0, 0, "Hello, ESPHome!");
      it.print(0, 1, "LCD Test OK!");

# Status LED (Optional)
status_led:
  pin: D4

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional fallback AP configuration
  ap:
    ssid: "1602-Testing-AP"
    password: "fallback-password"

# Enable web server for testing (optional)
web_server:

# API & OTA for ESPHome
api:
ota:
  platform: esphome
